version: '3.7'

services:
  app:
    image: jwilder/whoami
    deploy: &global
      mode: global
    networks: &net
      - net
    ports:
      - 8080:8000

  mgmt:
    image: lazyteam/lazydocker
    deploy: *global
    networks: *net
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  net:
    driver: overlay
