version: '3.7'

services:
  vagrant:
    image: kenney/vagrant-alpine
    working_dir: "/vagrant"
    volumes:
      - ./Vagrantfile:/vagrant/Vagrantfile
      - ./bionic-server-cloudimg-amd64-vagrant.box:/vagrant/bionic-server-cloudimg-amd64-vagrant.box
    command: "bash -c 'vagrant up'"
    entrypoint: ""
