version: '3.7'

services:
  nw:
    image: blacklabelops/virtualbox
    privileged: true
    working_dir: /root
    volumes:
      - /dev:/dev
      - .:/root
    ports:
      - 8081:80
    entrypoint: ["/bin/vagrant"]
    command: ["up"]
