#!/bin/bash

### BEGIN INIT INFO
# Provides:             nw
# Required-Start:       docker
# Required-Stop:        docker
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    nw daemon
### END INIT INFO

STACK=nw
PATH=/opt/nw-project

case "$1" in
start)
    docker stack deploy -c ${PATH}/docker-compose.yml $STACK
;;
status)
    docker service ls
;;
stop)
    docker stack rm $STACK
    docker system prune -f
    docker volume prune -f
    docker network prune -f
;;
restart)
    $0 stop
    sleep 5
    $0 start
;;
*)
    echo "Options: $0 {start|status|stop|restart}"
    exit 1
esac
