#!/bin/bash

NW_PATH=/opt/nw-project

if [ `id -u` -ne 0 ]; then
    echo "sudo is required"
    exit 1
fi

case "$1" in
start)
    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
;;
status)
    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
;;
stop)
    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
;;
*)
    echo "Options: $0 {start|status|stop}"
    exit 1
esac
