#!/bin/bash

VAGRANT_PATH=/opt/nw-project

case "$1" in
up)
    VAGRANT_PATH=$VAGRANT_PATH vagrant $1
;;
status)
    vagrant $1
;;
destroy)
    VAGRANT_PATH=$VAGRANT_PATH vagrant $1
;;
*)
    echo "Options: $0 {destroy|status|up}"
    exit 1
esac
