#!/bin/bash

NW_PATH=/opt/nw-project

if [ `id -u` -ne 0 ]; then
    echo "sudo is required"
    exit 1
fi

case "$1" in
up)
    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
;;
status)
    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
;;
destroy)
    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
;;
*)
    echo "Options: $0 {destroy|status|up}"
    exit 1
esac
